# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger: none

resources:
  pipelines:
  - pipeline: application-ci
    source: 'Run linting, test and sonarqube'
    trigger: true

variables:
- template: pipeline-variables.yml

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
    steps:
    - script: |
        docker buildx create --use --name multiplatform-builder || true
        docker buildx build \
          --platform linux/amd64 \
          --tag $(containerRegistry)/$(imageRepository):$(tag) \
          --tag $(containerRegistry)/$(imageRepository):latest \
          --push \
          -f $(dockerfilePath) \
          $(Build.SourcesDirectory)/src/azure-sa
      displayName: Build and Push (amd64)
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: Deploy Manifests
    pool:
      name: Default
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(azureSubscriptionConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(resourceGroupName) --name $(aksClusterName) --overwrite-existing
          kubectl apply -f src/azure-sa/k8s/
      displayName: 'Apply Kubernetes Manifests'
