# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger: none

resources:
  pipelines:
  - pipeline: application-ci
    source: 'Run linting, test and sonarqube'
    trigger: true

variables:
- template: pipeline-variables.yml

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    - script: |
        docker build \
          --tag $(containerRegistry)/$(imageRepository):$(tag) \
          --tag $(containerRegistry)/$(imageRepository):latest \
          -f $(dockerfilePath) \
          $(Build.SourcesDirectory)/src/azure-sa
        
        docker push $(containerRegistry)/$(imageRepository):$(tag)
        docker push $(containerRegistry)/$(imageRepository):latest
      displayName: Build and Push (standard)

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: Deploy Manifests
    pool:
      name: Default
    steps:
    - script: |
        echo "Debugging Variable:"
        echo "azureSubscriptionConnection is: $(azureSubscriptionConnection)"
      displayName: 'Debug Variable'

    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(azureSubscriptionConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(resourceGroupName) --name $(aksClusterName) --overwrite-existing
          kubectl apply -f src/azure-sa/k8s/
      displayName: 'Apply Kubernetes Manifests'
