trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - src/azure-sa/infra

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - src/azure-sa/infra

resources:
  repositories:
  - repository: self

pool:
  name: Default

variables:
- template: pipeline-variables.yml

stages:
- stage: Test
  displayName: Run linting and tests
  jobs:
  - job: Test
    displayName: Test
    steps:
    - task: SonarQubePrepare@8
      inputs:
        SonarQube: 'filevault-sonarqube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'filevault-sonarqube'
        cliProjectName: 'filevault-sonarqube'
        cliSources: 'src/azure-sa'
    - bash: |
        NEW_PARAMS=$(echo $SONARQUBE_SCANNER_PARAMS | sed 's/"sonar.branch.name":"[^"]*"//g' | sed 's/"sonar.pullrequest.key":"[^"]*"//g' | sed 's/"sonar.pullrequest.branch":"[^"]*"//g' | sed 's/"sonar.pullrequest.base":"[^"]*"//g' | sed 's/"sonar.pullrequest.provider":"[^"]*"//g' | sed 's/,,/,/g' | sed 's/,}/}/g' | sed 's/{,/{/g')
        echo "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$NEW_PARAMS"
        echo "Filtered out sonar.branch.name and sonar.pullrequest.* for Community Edition"
      displayName: 'Fix SonarQube Community Parameters'
    - script: npm install
      workingDirectory: src/azure-sa
      displayName: 'Install dependencies'
    - script: npm run lint
      workingDirectory: src/azure-sa
      displayName: 'Run linting'
    - script: npm run test
      workingDirectory: src/azure-sa
      displayName: 'Run jest tests'
    - task: SonarQubeAnalyze@8
      env:
        sonar.branch.name: ""
    - task: SonarQubePublish@8
      inputs:
        pollingTimeoutSec: '300'

- stage: Build_and_Deploy
  displayName: Build and Deploy
  dependsOn: Test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: Build
    displayName: Build Container
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    - script: |
        docker build \
          --platform linux/amd64 \
          --tag $(containerRegistry)/$(imageRepository):$(tag) \
          --tag $(containerRegistry)/$(imageRepository):latest \
          -f $(dockerfilePath) \
          $(Build.SourcesDirectory)/src/azure-sa
        
        docker push $(containerRegistry)/$(imageRepository):$(tag)
        docker push $(containerRegistry)/$(imageRepository):latest
      displayName: Build and Push (standard)

  - job: Deploy
    displayName: Deploy Manifests
    dependsOn: Build
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'filevault-azure-connection' 
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(resourceGroupName) --name $(aksClusterName) --overwrite-existing
            
          kubectl apply -f src/azure-sa/k8s/
      displayName: 'Apply Kubernetes Manifests and Secrets'
