trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/azure-sa/infra

pool:
  name: Default

stages:
- stage: Terraform_Check
  displayName: 'Terraform Check'
  jobs:
  - job: Terraform_Validate
    displayName: 'Validate Terraform'
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - script: |
        terraform fmt -check -recursive
      displayName: 'Terraform Format Check'
      workingDirectory: src/azure-sa/infra

    - script: |
        terraform init -backend=false
      displayName: 'Terraform Init'
      workingDirectory: src/azure-sa/infra

    - script: |
        terraform validate
      displayName: 'Terraform Validate'
      workingDirectory: src/azure-sa/infra
