apiVersion: apps/v1
kind: Deployment
metadata:
  name: filevault-deployment
  labels:
    app: filevault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filevault # Must match template labels below
  template:
    metadata:
      labels:
        app: filevault # Must match selector above
    spec:
      containers:
      - name: filevault
        image: filevaultsaacr.azurecr.io/lachlandowfilevault:latest
        ports:
        - containerPort: 3000
        env:
        - name: AZURE_STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: filevault-k8s-secret
              key: AZURE_STORAGE_ACCOUNT_KEY
        - name: AZURE_STORAGE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: filevault-k8s-secret
              key: AZURE_STORAGE_ACCOUNT_NAME
        - name: AZURE_CONTAINER_NAME
          value: "uploads"
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kv-provider"