apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "file-vault-secret-vault"
    objects: |
      array:
        - |
          objectName: storage-account-key
          objectType: secret
          alias: AZURE_STORAGE_ACCOUNT_KEY
        - |
          objectName: storage-account-name
          objectType: secret
          alias: AZURE_STORAGE_ACCOUNT_NAME
    tenantId: "76d8557f-9da9-430b-8107-ae2c06fe61f8" # From your logs
  secretObjects:
  - secretName: filevault-k8s-secret
    type: Opaque
    data:
    - objectName: AZURE_STORAGE_ACCOUNT_KEY
      key: AZURE_STORAGE_ACCOUNT_KEY
    - objectName: AZURE_STORAGE_ACCOUNT_NAME
      key: AZURE_STORAGE_ACCOUNT_NAME