apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "" # CSI driver uses the system-assigned identity by default
    keyvaultName: "file-vault-secret-vault"
    objects: |
      array:
        - |
          objectName: storage-account-key
          objectType: secret
          alias: AZURE_STORAGE_ACCOUNT_KEY
    tenantId: "REPLACE_WITH_YOUR_TENANT_ID"
  secretObjects:
  - secretName: filevault-k8s-secret # This creates a native K8s secret for your env vars
    type: Opaque
    data:
    - objectName: AZURE_STORAGE_ACCOUNT_KEY
      key: AZURE_STORAGE_ACCOUNT_KEY