apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: filevault-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       filevault-deployment
  updatePolicy:
    updateMode: "Off" # Use "Auto" to allow VPA to update pods, "Off" for recommendations only
